nodeLinker: node-modules

# Ensure consistent package manager
packageManager: "yarn@1.22.22"

# Enable zero-installs for better performance
enableGlobalCache: true

# Ensure deterministic installs
enableScripts: true

# Use the same registry for all packages
npmRegistryServer: "https://registry.npmjs.org/"
